title: webtool
email: sainidhanesh58@gmail.com
description: >-
  Webtool offers hundreds of free online tools, including calculators, image downloaders, time converters, current for all time zones, QR codes, SEO tools etc.
baseurl: ""
url: "https://www.webtool.live"
twitter_username: jekyllrb
github_username: jekyll

permalink: :title/
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: :title/
  length:
    output: true
    permalink: length/:title
  date:
    output: true
    permalink: date/:title
  datastorage:
    output: true
    permalink: datastorage/:title
  worldclock:
    output: true
    permalink: worldclock/:title
